# Test code
import sys
sys.path.append("/Users/jeffreyjahja/Documents/Uni/FYP/Code/FYPSAR/third-party") #Please change directory accordingly
#print(sys.path)
import YanAPI

#    初始化SDK
# *  @param robot_ip  参数：机器人IP地址
# *  @return 无返回值
def robot_pause():
    print(YanAPI.get_current_motion_play_state()['data']['status'])
    while YanAPI.get_current_motion_play_state()['data']['status'] != "idle":
        #print("robot running")
        pass

ip_addr = '160.69.69.103'
YanAPI.yan_api_init(ip_addr)
print(YanAPI.get_motion_list())
#print(robot_actions)

YanAPI.set_robot_volume_value(100)
#YanAPI.set_robot_language('en')
#YanAPI.start_voice_tts('Hello, I am Yanshee, I am ready to play some music', interrupt=False)
#YanAPI.start_play_motion(name = 'ActionAging1', speed = 'slow')
#interrupt = input("Type X to stop: ")
#print(YanAPI.get_motion_list_value())
YanAPI.start_voice_tts("Head Stretch")
YanAPI.start_play_motion(name = 'HeadStretch')
robot_pause()
YanAPI.start_play_motion(name = 'reset')
YanAPI.start_voice_tts("Shoulder Stretch")
YanAPI.start_play_motion(name = 'ShoulderStretch')
robot_pause()
YanAPI.start_play_motion(name = 'reset')
YanAPI.start_voice_tts("Upper and Lower Stretch")
YanAPI.start_play_motion(name = 'UpperLower')
robot_pause()
YanAPI.start_play_motion(name = 'reset')
YanAPI.start_voice_tts("Foot Rotation")
YanAPI.start_play_motion(name = 'FootRotation')
robot_pause()
YanAPI.start_play_motion(name = 'reset')
YanAPI.start_voice_tts("Wrist Stretch")
YanAPI.start_play_motion(name = 'WristStretch')
robot_pause()
YanAPI.start_play_motion(name = 'reset')
YanAPI.start_voice_tts("SideBend")
YanAPI.start_play_motion(name = 'SideBend')
robot_pause()
YanAPI.start_play_motion(name = 'reset')
YanAPI.start_voice_tts("Backwards Arch")
YanAPI.start_play_motion(name = 'BackwardsArch')
robot_pause()
YanAPI.start_play_motion(name = 'reset')
YanAPI.start_voice_tts("Pectoral Stretch")
YanAPI.start_play_motion(name = 'Pectoral')
robot_pause()
YanAPI.start_play_motion(name = 'reset')
YanAPI.start_voice_tts("Forward Stretch")
YanAPI.start_play_motion(name = 'ForwardStretch')
robot_pause()
YanAPI.start_play_motion(name = 'reset')
YanAPI.start_voice_tts("Heel Raise")
YanAPI.start_play_motion(name = 'HeelRaise')
robot_pause()
YanAPI.start_play_motion(name = 'reset')
YanAPI.start_voice_tts("Head Roll")
YanAPI.start_play_motion(name = 'HeadRoll')
robot_pause()
YanAPI.start_play_motion(name = 'reset')
YanAPI.start_voice_tts("Chin Tuck")
YanAPI.start_play_motion(name = 'ChinTuck')
robot_pause()
YanAPI.start_play_motion(name = 'reset')
YanAPI.start_voice_tts("Shoulder Roll")
YanAPI.start_play_motion(name = 'ShoulderRoll')
robot_pause()
YanAPI.start_play_motion(name = 'reset')
YanAPI.start_voice_tts("Eye Rest")
YanAPI.start_play_motion(name = 'EyeRest')
robot_pause()
YanAPI.start_play_motion(name = 'reset')